site_name: Whats The Point
theme:
  name: material
  logo: ""

  features:
    #- navigation.tabs # uncomment this to make navigation on top
    - navigation.sections
    - toc.integrate
    #- navigation.footer

nav:
- 'index.md'
- 'game_time.md'
- 'peoplesinvestments.md'
- 'discuss1.md'
- 'peoplesregret.md'
- 'round2.md'
- 'peoplesinsuranceinvestments.md'
- 'discuss2.md'
- 'round3.md'
- 'discuss3.md'
- 'allocate.md'
- 'peoplessave.md'
- 'insvsavediscuss.md'
- 'savingspoints.md'
- 'youdo.md'
- 'bye.md'

plugins:
  - search
  - macros

extra:
  kobo_form_id: iusvpk4H
  analytics:
    provider: google
    property: G-YM4PVFJE0F

extra_javascript:
  - javascripts/slide_manager.js
  - javascripts/kobo_loader.js # should no longer be necessary now that there is slide-manager.js

extra_css:
  - stylesheets/styles.css
